/**
 * Code is auto-generated by Application Logic, DO NOT EDIT.
 * @version(2.0)
 */
const LCAPApplicationService = require('@sap/low-code-event-handler');
const before_Changerequests_Create_Update = require('./code/before-changerequests-create-update');

class hackathonSrv extends LCAPApplicationService {
    async init() {

        this.before(['CREATE', 'UPDATE'], 'ChangeRequests', async (request) => {
            await before_Changerequests_Create_Update(request);
        });

        return super.init();
    }
}


module.exports = {
    hackathonSrv
};